DROP TABLE IF EXISTS "Computers";
CREATE TABLE Computers(
 cID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
 cName VARCHAR(255) NOT NULL,
 cType VARCHAR(511) NOT NULL,
cBuilt BOOLEAN NOT NULL,
cBuiltYear INT NOT NULL
);
DROP TABLE IF EXISTS "P_C_con";
CREATE TABLE P_C_con (
  PID INT,
  CID INT,
  FOREIGN KEY (PID) REFERENCES People (PID),
  FOREIGN KEY (CID) REFERENCES Computers (CID),
  PRIMARY KEY (PID, CID)
 );
DROP TABLE IF EXISTS "People";
CREATE TABLE People (
 PID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE ,
 pName VARCHAR(255) NOT NULL ,
 pSex VARCHAR(1) NOT NULL,
 pBirthYear INTEGER NOT NULL ,
 pDeathYear INTEGER,
 pTuring BOOLEAN NOT NULL,
 pTuringYear INT
 );
